//
//  DetailPresenter.swift
//  DesafioMyFreeComm-iOS
//
//  Created by Hundily Cerqueira Silva on 29/04/19.
//  Copyright (c) 2019 Hundily Cerqueira Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentSomething(response: Detail.Something.Response)
    func displayRepositoryDetail(repositoryDetail: Home.Something.Items)
}

class DetailPresenter: DetailPresentationLogic
{
 
    
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Detail.Something.Response)
  {
    let viewModel = Detail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func displayRepositoryDetail(repositoryDetail: Home.Something.Items)
    {
        print("displayRepositoryDetail", repositoryDetail)
    }
}
