//
//  DetailViewController.swift
//  DesafioMyFreeComm-iOS
//
//  Created by Hundily Cerqueira Silva on 29/04/19.
//  Copyright (c) 2019 Hundily Cerqueira Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailDisplayLogic: class
{
  func displaySomething(viewModel: Detail.Something.ViewModel)
}

class DetailViewController: UIViewController, DetailDisplayLogic
{
  var interactor: DetailBusinessLogic?
  var router: (NSObjectProtocol & DetailRoutingLogic & DetailDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = DetailInteractor()
    let presenter = DetailPresenter()
    let router = DetailRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
    
    tableViewDetail.delegate = self
    tableViewDetail.dataSource = self
    
    registerCell()
    getRepositoryDetail()
  }
  
  // MARK: Do something
  
    @IBOutlet weak var tableViewDetail: UITableView!
    //@IBOutlet weak var nameTextField: UITextField!
    
    func registerCell()
    {
         tableViewDetail.register(UINib(nibName: "DetailTableViewCell", bundle: Bundle.main), forCellReuseIdentifier: "detailCell")
    }
    
    func getRepositoryDetail()
    {
        interactor?.getRepositoryDetail()
    }
  
  func doSomething()
  {
    let request = Detail.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Detail.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}


extension DetailViewController: UITableViewDataSource, UITableViewDelegate {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: "detailCell") as! DetailTableViewCell
//
//        if let forks_number = arrayTableData[indexPath.row].forks_count,
//            let start_number = arrayTableData[indexPath.row].stargazers_count {
//            cell.labelNumberForks.text = "\(forks_number)"
//            cell.labelNumberStart.text = "\(start_number)"
//        }
//
//        cell.labelNewRepository.text = arrayTableData[indexPath.row].name
//        cell.labelNameUser.text = arrayTableData[indexPath.row].owner?.login
//
//        cell.labelUserNameAndLastName.text = arrayTableData[indexPath.row].full_name
//        cell.labelRepositoryDiscription.text = arrayTableData[indexPath.row].description
//        cell.imageAvatar.sd_setImage(with: URL(string: arrayTableData[indexPath.row].owner?.avatar_url ?? ""), placeholderImage: UIImage(named: "placeholder.png"))
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 176
    }
    
    func handleRefresh(_ refreshControl: UIRefreshControl) {
        refreshControl.endRefreshing()
    }
}
