//
//  HomeInteractor.swift
//  DesafioMyFreeComm-iOS
//
//  Created by Hundily Cerqueira Silva on 28/04/19.
//  Copyright (c) 2019 Hundily Cerqueira Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func getTableDataInterector()
}

protocol HomeDataStore
{
  var repositoryDetail: Home.Something.Items? { get }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var repositoryDetail: Home.Something.Items?
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  
  // MARK: Do something
    func getTableDataInterector() {
        worker = HomeWorker()
        worker?.getTableData(responseRequest: { (response) in
            if let items = response.items {
//                self.repositoryDetail = response.items
//                print(items)
                self.presenter?.displayTableData(response: items)
            }
        }, failed: { (err) in
            print(err)
        })
    }
}
