//
//  HomeWorker.swift
//  DesafioMyFreeComm-iOS
//
//  Created by Hundily Cerqueira Silva on 28/04/19.
//  Copyright (c) 2019 Hundily Cerqueira Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

typealias loginResponseHandler = (_ response: Home.Something.Request) -> ()

class HomeWorker
{
        var url: String = "https://api.github.com/search/repositories?q=language:Java&sort=stars&page=1"
        
    func getTableData(responseRequest: @escaping(loginResponseHandler), failed: @escaping(loginResponseHandler)){
            Alamofire.request(url, method: .get, parameters: nil, encoding: JSONEncoding.default).responseJSON(completionHandler: {
                response in
                do {
                    if let res = response.data {
                        let infos = try JSONDecoder().decode(Home.Something.Request.self, from: res)
                        responseRequest(infos)
                    }
                } catch let err {
                    failed(err as! Home.Something.Request)
                }
            })
    }
    
    func doSomeWork() {
        
    }

}
